### ISSUE TITLE
Minimize models without evaluating them

### ISSUE THREAD

**Issue by tchajed** [vmware-research/temporal-verifier#37]
It occurred to me while fixing #26 that one reason evaluation is slow is that the models are large, and this is because they aren't yet minimized. However, minimization only requires knowing the universe cardinalities and not constructing the full `Interpretation`s, and we can extract this very efficiently with some basic sexp parsing.

After minimization model evaluation should generally be much faster; for example the slow test we currently have involves a `node` sort with a universe of 78 elements, and evaluating a function of two `node`s on about 6,000 inputs. Probably that universe could be of size 3 or 4.

**Comment by wilcoxjay** [comment]
Here's an alternative trick you can use to avoid needing to know the initial cardinalities: "minimize up" rather than "minimizing down". To minimize, you start by asking the solver if the formula is satisfiable if all universes have size 1. If not, try with all universes having size 2, and so on. Once you find a size that works, you can then "minimize down" to finish minimizing in a way that allows the universes to have different sizes from each other. This algorithm doesn't even need to call `(get-model)` much less parse the output. You could also speed it up by using "upward binary search" by doubling the size each time instead of incrementing by 1.
